name: Deploy Workspace

on:
  push:
    branches: [prod]

jobs:
  deploy:
    name: Deploy Workspace test
    runs-on: ubuntu-latest
    steps:
    - name: testing deploy
      uses: appleboy/ssh-action@master
      with:
        host: shell.xshellz.com
        port: 22
        username: indreshp
        key: ${{ secrets.SSH_SECRET }}
        script: |
          cd /home/indreshp/hi
          # git checkout .
          # git fetch origin
          # git reset --hard origin/prod
          # yarn install
          # yarn build
          # pm2 restart react-deploy-test
          cd ..
          # /usr/bin/rm -rf public_html/*
          # cp -r react-deploy-test/build/* public_html/
